### ISSUE TITLE
Region restrictions are not working

### ISSUE THREAD

**Issue by Nafraju** [TyruswooStudio/Tyruswoo_AltimitMovement-MZ#6]
Hi,
![grafik](https://github.com/user-attachments/assets/b8526934-7a8e-406d-bd53-2b1aba55f647)

YEP_RegionRestrictions
is not working.

**Comment by McKathlin** [comment]
Thank you for reporting this issue! I'm trying to make sense of it so that I can test on the right plugin combination. Based on what I've found online, YEP_RegionRestrictions is for RPG Maker MV only. The equivalent for RPG Maker MZ is [VisuMZ_1_EventsMoveCore.js](http://www.yanfly.moe/wiki/Events_and_Movement_Core_VisuStella_MZ), which is a paid plugin. However, your screenshot shows that you're in RPG Maker MZ working with YEP_RegionRestrictions. It looks like what you have is an unofficial port. Out of respect for [Yanfly's wishes](http://www.yanfly.moe/wiki/Official_Statement_from_Yanfly_Regarding_Porting_of_Plugins), I advise against using it in a published game, and I am unwilling to provide compatibility support for it.

What I can do for you is recommend our free plugin [Tyruswoo Map Properties MZ](https://www.tyruswoo.com/downloads/rpg-maker-plugin-downloads/#map-properties-mz), which provides the same feature: specific region numbers can block or allow NPCs or players. I'm not sure we've tested Tyruswoo Altimit Movement's compatibility with this feature yet, so I'll get right on it. I'm glad you got us thinking about it.

--Kathy

**Comment by Nafraju** [comment]
> Thank you for reporting this issue! I'm trying to make sense of it so that I can test on the right plugin combination. Based on what I've found online, YEP_RegionRestrictions is for RPG Maker MV only. The equivalent for RPG Maker MZ is [VisuMZ_1_EventsMoveCore.js](http://www.yanfly.moe/wiki/Events_and_Movement_Core_VisuStella_MZ), which is a paid plugin. However, your screenshot shows that you're in RPG Maker MZ working with YEP_RegionRestrictions. It looks like what you have is an unofficial port. Out of respect for [Yanfly's wishes](http://www.yanfly.moe/wiki/Official_Statement_from_Yanfly_Regarding_Porting_of_Plugins), I advise against using it in a published game, and I am unwilling to provide compatibility support for it.
> 
> What I can do for you is recommend our free plugin [Tyruswoo Map Properties MZ](https://www.tyruswoo.com/downloads/rpg-maker-plugin-downloads/#map-properties-mz), which provides the same feature: specific region numbers can block or allow NPCs or players. I'm not sure we've tested Tyruswoo Altimit Movement's compatibility with this feature yet, so I'll get right on it. I'm glad you got us thinking about it.
> 
> --Kathy

Sure, I checked your free Plugin [Tyruswoo Map Properties MZ](https://www.tyruswoo.com/downloads/rpg-maker-plugin-downloads/#map-properties-mz),

![grafik](https://github.com/user-attachments/assets/6e4006a4-aa48-4999-b2af-612107d19cdd)

But this only works if Tyruswoo_AltimitMovement is OFF.
The issue should be located in this 3 'Blocks':

![grafik](https://github.com/user-attachments/assets/7399566c-044b-4ef9-b979-45f4dc8fdee8)

**Comment by Nafraju** [comment]
#NOTE :
To Plugin [Tyruswoo Map Properties MZ](https://www.tyruswoo.com/downloads/rpg-maker-plugin-downloads/#map-properties-mz),

![grafik](https://github.com/user-attachments/assets/afc742a6-33ac-4789-a007-81aa81415458)

**Comment by McKathlin** [comment]
Yes, I noticed this issue when I tested the plugins together yesterday. My plan is, when the Map Properties plugin is present, Altimit Movement will calculate a collision mesh for players and a different collision mesh for events. I'll let you know as soon as I have it working.

**Comment by McKathlin** [comment]
> #NOTE : To Plugin [Tyruswoo Map Properties MZ](https://www.tyruswoo.com/downloads/rpg-maker-plugin-downloads/#map-properties-mz),
> 
> ![grafik](https://private-user-images.githubusercontent.com/111924807/356188347-afc742a6-33ac-4789-a007-81aa81415458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTQzMTcsIm5iZiI6MTcyMzExNDAxNywicGF0aCI6Ii8xMTE5MjQ4MDcvMzU2MTg4MzQ3LWFmYzc0MmE2LTMzYWMtNDc4OS1hMDA3LTgxYWE4MTQxNTQ1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMDQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmRkZTFjZmJlZWNhN2ZmNjkwYjIxMjBlNjQxMTI1MDQ2N2Y0ZGQ2NmNiNTVjNDQyNzcwNGQ2NGVhOWZhNjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Pp6sioaySzp3SL0y_wDe_50AOc9gbQR9RbDiDPsaxc)

Good catch! Your point about zeroes entered for region numbers in our MZ Map Properties plugin is applicable with or without other plugins involved. I would encourage you to bring this up as a new issue in our [MZ Map Properties repository](https://github.com/TyruswooStudio/Tyruswoo_MapProperties-MZ). That will help us keep track of it; I'm afraid it'll get forgotten here once I close the Altimit Movement compatibility issue.

**Comment by McKathlin** [comment]
I've updated Tyruswoo Map Properties and Tyruswoo Altimit Movement to work together as intended. Below are links to the cross-compatible versions:

- [Tyruswoo Altimit Movement v0.9.2](https://github.com/TyruswooStudio/Tyruswoo_AltimitMovement-MZ/releases/tag/v0.9.2)
- [Tyruswoo Map Properties v2.1.0](https://github.com/TyruswooStudio/Tyruswoo_MapProperties-MZ/releases/tag/v2.1.0)

Per your note on Region Zero, this new version of Map Properties also ignores zeroes in its region lists and has a note in the help text to that effect. (We strive to make our help text complete, while also making our plugin easy to use for those who haven't read or don't remember all the help text.)
