### ISSUE TITLE
Important missing note in the plugin help

### ISSUE THREAD

**Issue by Nafraju** [TyruswooStudio/Tyruswoo_AltimitMovement-MZ#7]
`$gamePlayer.x`
and 
`$gamePlayer.y`
no longer work for position queries because they now contain decimal values.

However:
with 
`Math.round($gamePlayer.x)`
and 
`Math.round($gamePlayer.y)`
it works perfectly.

And:
So far I don't have any MapEvents that move using pixel-movement (**_I don't even know if that's possible?_**),
so I haven't tested it or checked whether it also applies to `$gameMap.event(this.eventId()).x` and `$gameMap.event(this.eventId()).y`.

For stationary MapEvents or MapEvents that move according to standard, it still works without Math.round()

**Comment by McKathlin** [comment]
That's a good point. I'll make a note of that in the documentation and look into what might need to change in event command code to make Tyruswoo Altimit Movement more event-friendly.

**Comment by Nafraju** [comment]
> That's a good point. I'll make a note of that in the documentation 
YES
> and look into what might need to change in event command code to make Tyruswoo Altimit Movement more event-friendly.
NO

I would NOT change that the `$gamePlayer.x` and `$gamePlayer.y` gives decimal values.
Because this is even more correct.
Example: 
So I can ask if the player enters a tile .. is in middle .. or leaves the tile.
Without recalculating it (via `$gamePlayer.X` and `$gamePlayer.Y`) from the screenvalues.

So this is NOT a bug !
In this case it **_truly_** is a massive-important feature !
Please, dont remove this feature.

Just let the users know about it in the help.

**Comment by McKathlin** [comment]
You've got a good point. Whether to make `$gamePlayer.x` and `$gamePlayer.y` in Altimit function as the exact floating-point value or as the nearest integer is a tricky decision with pros and cons. Until my team has a clear plan, I'd best stick with the current implementation and simply add a note to the documentation.

**Comment by McKathlin** [comment]
Hi @Nafraju, per your recommendation, we've added a note on the plugin's effect on player X and Y coordinates to the plugin's help text and README. We've made [patch release 0.9.5](https://github.com/TyruswooStudio/Tyruswoo_AltimitMovement-MZ/releases/tag/v0.9.5) to share this change. Thank you for your attention to this detail.
